apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-resource
  namespace: argocd
spec:
  project: default
  source:
    path: k8s-resources
    repoURL: https://github.com/jagyugyaerik/argo-cd-demo
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: k8s-reources